version: '3.8'

services:
  verbum:
    build: .
    ports:
      - "5020:5020"
    environment:
      - HOST=0.0.0.0
      - PORT=5020
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5020/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
