services:
  verbum:
    build: .
    ports:
      - "5020:5020"
    volumes:
      # Persist search history data
      - verbum_data:/app/data
    environment:
      # Server configuration
      - HOST=0.0.0.0
      - PORT=5020
      # Data persistence
      - SEARCH_HISTORY_DIR=/app/data
      # Content filtering disabled for academic/research use
      - ENABLE_PROFANITY_FILTER=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5020/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  verbum_data:
    driver: local
